### ISSUE TITLE
Fail on windows

### ISSUE THREAD

**Issue by barsan-md** [ahamed/jext-cli#1]
**Describe the bug**
Everithing worked correctly until "Generating the component metadata..."

Then an error happened
```
Do you confirm component creation [yes]?
Generating the component metadata...
PHP Warning:  file_put_contents(/jext.json): Failed to open stream: Permission denied in C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\BaseController.php on line 141

Warning: file_put_contents(/jext.json): Failed to open stream: Permission denied in C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\BaseController.php on line 141
Metadata generation completed.

Creating component core files...
PHP Fatal error:  Uncaught Exception: You are too early to get the meta data or the `jext.json` file has been deleted! in C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\BaseController.php:108
Stack trace:
#0 C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\ComponentController.php(184): Ahamed\Jext\Controllers\BaseController->getMeta('restaurant-mana...')
#1 C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\ComponentController.php(328): Ahamed\Jext\Controllers\ComponentController->createComponentFiles()
#2 C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Application.php(70): Ahamed\Jext\Controllers\ComponentController->run(Array)
#3 C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\bin\jext-cli(11): Ahamed\Jext\Application->run(Array)
#4 {main}
  thrown in C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\BaseController.php on line 108

Fatal error: Uncaught Exception: You are too early to get the meta data or the `jext.json` file has been deleted! in C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\BaseController.php:108
Stack trace:
#0 C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\ComponentController.php(184): Ahamed\Jext\Controllers\BaseController->getMeta('restaurant-mana...')
#1 C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\ComponentController.php(328): Ahamed\Jext\Controllers\ComponentController->createComponentFiles()
#2 C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Application.php(70): Ahamed\Jext\Controllers\ComponentController->run(Array)
#3 C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\bin\jext-cli(11): Ahamed\Jext\Application->run(Array)
#4 {main}
  thrown in C:\Users\User\Downloads\Browser\jext-cli-1.0.0-beta.1\src\Controllers\BaseController.php on line 108
```

I'm on windows using xampp

PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:40) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies

Composer version 2.0.11 2021-02-24 14:57:23

**Comment by barsan-md** [comment]
It works when the terminal is run as administrator. Thanks

**Comment by ahamed** [comment]
Which process have you been followed for installing into windows? Can you run it globally? I mean run from anywhere by CMD?

**Comment by barsan-md** [comment]
I can run php and composer globally from command line by adding them to the path environment variable. Then running it is easily using `php ./bin/jext-cli`
As for the install it runs well, it opens a bash window, I think it is because I installed git (https://git-scm.com/) so I have it installed in "C:\Program Files\Git\git-bash.exe"

**Comment by ahamed** [comment]
I haven't the opportunity to test in windows. The `install.sh` file is written for `macOS` and `Linux` based Operating Systems.

The idea is to run the `jext-cli` command globally, then go to the Joomla! 4 project root directory and run the commands e.g `ject-cli --component todo` etc.

If you can run the `jext-cli` command globally in windows you can contribute to the project. It would be a great pleasure to be.

**Comment by barsan-md** [comment]
I will keep an eye on the project, thanks. Just a suggestion here but did you consider making it a web application instead of command line. Developers using Joomla already have some environment to test the component they are making. Maybe creating an html UI and accessing it using the browser may be easier for most of the people, also it would solve the problem of OS difference.

**Comment by ahamed** [comment]
Thank you @barsan-md for your suggestion. Actually, this project is for developers who develop extensions. If you are an extension developer then for developing a component you have to create a good number of repetitive codes which you might write before.
So, by using this tool one developer can easily create a component by writing just one command, and provide some meta-information.
